name: Deploy To EC2

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: jar 파일 만들기
        run: echo "${{ secrets.APPLICATION_DB_PROPERTIES }}" > ./agilementor

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ./agilementor
          target: ~/server

      - name: SSH로 EC2에 접속해 앱 실행하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: sh ~/server/run.sh
